#!/bin/zsh
#
# Usage: jwt-decode <jwtstring>
# Description: decodes jwt string into human-readable json
#
# https://www.pgrs.net/2022/06/02/simple-command-line-function-to-decode-jwts/

jwt-decode() {
  jq -R 'split(".") |.[0:2] | map(gsub("-"; "+") | gsub("_"; "/") | gsub("%3D"; "=") | @base64d) | map(fromjson)' <<<$1
}
